"use strict";
/* The cards the board ships with, inserted once into an empty table.
   Kept in step with the SEEDS array in the standalone index.html. */

module.exports = [
  {id:"tr-ramp",    col:"new", title:"Transition ramp fell in",
   reporter:"Nick Wesley", loc:"Wild Mile", prio:"High", date:"2026-04-04",
   desc:"Photo in Slack; couldn't file via the bug form.", link:""},
  {id:"eink-plug",  col:"new", title:"Eink power plug is not accessible",
   reporter:"Nick Wesley", loc:"Wild Mile", prio:"Medium", date:"2026-06-29",
   desc:"", link:""},
  {id:"geese",      col:"new", title:"Geese nesting in wake barriers",
   reporter:"Maya Kelly", loc:"Wake barriers", prio:"Medium", date:"2026-04-09",
   desc:"Geese are pulling wake barrier material for nests.", link:""},
  {id:"deck-board", col:"new", title:"Cracked, bouncy deck board near second gathering nook",
   reporter:"Maya Kelly", loc:"Second gathering nook", prio:"High", date:"2025-07-18",
   desc:"Feels bouncy underfoot; expected to break.", link:""},
  {id:"natgeo",     col:"new", title:"Nat Geo island hanging on its anchors",
   reporter:"Phil Nicodemus", loc:"Nat Geo island", prio:"High", date:"2025-10-28",
   desc:"", link:""},
  {id:"north-old",  col:"new", title:"Furthest north old islands jacked up",
   reporter:"Phil Nicodemus", loc:"North old islands", prio:"Medium", date:"2025-10-28",
   desc:"", link:""},
  {id:"dropped-eq", col:"new", title:"Possible dropped equipment in river",
   reporter:"Phil Nicodemus", loc:"Wild Mile", prio:"Low", date:"2025-10-28",
   desc:"“We might have dropped this” — needs ID and retrieval.", link:""},
  {id:"fence",      col:"new", title:"Fence broken, needs ring gunning",
   reporter:"Sage Rossman", loc:"Fence", prio:"Low", date:"2024-10-23",
   desc:"", link:""},
  {id:"van-steer",  col:"new", title:"Van steering column leaking water",
   reporter:"Stephen Meyer", loc:"Van", prio:"Medium", date:"2025-09-13",
   desc:"Water comes out of the steering column when turning the wheel. Not install/maintenance proper.", link:""},
  {id:"prologis",   col:"scheduled", title:"Prologis fix needed before city tour",
   reporter:"Nick Wesley", loc:"Prologis", prio:"Urgent", date:"2026-06-02",
   desc:"City tour of Prologis was July 23; confirm whether still outstanding.", link:""},
  {id:"bugform",    col:"triaged", title:"Open bug-form submissions (Slack list)",
   reporter:"Issue submission form", loc:"Various", prio:"Medium", date:"",
   desc:"About a dozen submissions live in the Slack bug list; titles aren't readable from the channel feed, so copy them onto the board as they get triaged.",
   link:"https://urbanrivers.slack.com/lists/T049JE18R/F0839EZG03H"}
];
